const SEAT_TYPE = {
    BUSINESS: 'BUSINESS',
    ECONOMY: 'ECONOMY',
    PREMIUM_ECONOMY: 'PREMIUM_ECONOMY',
    FIRST_CLASS: 'FIRST_CLASS',
}

const BOOKING_STATUS = {
    BOOKED: 'BOOKED',
    CANCELLED: 'CANCELLED',
    INITIATED: 'INITIATED',
    PENDING: 'PENDING',
}

module.exports = {
    SEAT_TYPE,
    BOOKING_STATUS,
}